version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - checkout
      - run:
          name: "Shellcheck"
          command: "shellcheck bootstrap.sh"
  run:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: "Run bootstrap.sh"
          command: |
            # CircleCI's Mac executor comes pre-installed with this `six` python package
            # which conflicts with the bootstrap... uninstall first
            pip3 uninstall --yes six
            # run bootstrap
            ./bootstrap.sh | tee -a bootstrap.log
      - store_artifacts:
          path: ./bootstrap.log
      - store_artifacts:
          path: ./files/Brewfile.lock.json

workflows:
  version: 2
  build-run:
    jobs:
      - build
      - run:
          requires:
            - build
          filters:
            branches:
              only:
                - main
