version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - checkout
      - run:
          name: "Shellcheck"
          command: "shellcheck bootstrap.sh"
  run:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: "Run bootstrap.sh"
          command: "./bootstrap.sh | tee -a bootstrap.log"
      - store_artifacts:
          path: ./bootstrap.log

workflows:
  version: 2
  build-run:
    jobs:
      - build
      - run:
          requires:
            - build
          filters:
            branches:
              only:
                - master
