---
    - hosts: localhost
      connection: local

      tasks:
        - name: Install Kubernetes yum_repository
          yum_repository:
            name: kubernetes
            baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            description: "Kubernetes repo"
            enabled: yes
            gpgcheck: yes
            gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            repo_gpgcheck: yes
            state: present

        - name: Install mongodb-org yum_repository
          yum_repository:
            name: mongodb-org
            baseurl: https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/
            description: "MongDB repo"
            enabled: yes
            gpgcheck: yes
            gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc
            repo_gpgcheck: yes
            state: present

        # TIP: Now that you have added the HashiCorp repository, you can install Terraform, Vault, Consul, and Nomad
        # with the same command. https://learn.hashicorp.com/tutorials/packer/get-started-install-cli
        - name: Install Hashicorp yum_repository
          yum_repository:
            name: hashicorp
            baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
            description: Hashicorp Stable - $basearch
            enabled: yes
            gpgcheck: yes
            gpgkey: https://rpm.releases.hashicorp.com/gpg
            repo_gpgcheck: yes
            state: present

        - name: Install Yarn yum_repository
          yum_repository:
            name: yarn
            baseurl: https://dl.yarnpkg.com/rpm/
            description: "Yarn Repository"
            enabled: yes
            gpgcheck: yes
            gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
            repo_gpgcheck: yes
            state: present
