name: Scan Code for Secrets
'on':
  push:
    branches:
      - '**'
    tags:
      - '!**'
jobs:
  detect-secrets:
    name: check-for-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            detect-secrets
      - name: Run Yelp's detect-secrets
        run: |
          detect-secrets-hook --baseline .secrets.baseline $(git diff origin/main --name-only)
