name: Scan Code for Secrets
'on':
  push:
    branches:
      - '**'
    tags:
      - '!**'
jobs:
  detect-secrets:
    name: check-for-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            detect-secrets
      - name: Run Yelp's detect-secrets
        run: >
          detect-secrets scan --exclude-lines "secretName:" --exclude-secrets
          "abc123xyz456" > ./.secrets.baseline

          detect-secrets audit ./.secrets.baseline
      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >-
            build(detect-secrets): Commit the newly-generated .secrets.baseline
            file
